version: '3.3'
  
services:
  postventa_db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postventa
      - POSTGRES_USER=postventa
      - POSTGRES_PASSWORD=postventa
    ports:
      - '5433:5432'
    volumes:
      - ~/data_volums_docker/postventa_database:/var/lib/postgresql/data
  prod:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
        - 3000:3000
    env_file:
      - dev.env
    depends_on:
      - postventa_db